kind: API
apiVersion: api.ibm.com/v1
metadata:
  name: Petstore3
  namespace: Petstore
  version: '1.0'
  tags: []
  type: REST
spec:
  api-spec:
    $path: ./Petstore3-spec.json
  uriSchemes:
    $ref: Petstore:HTTPS:1.0
  policy-sequence:
    - $ref: Petstore:DPSeq:1.0
